use_frameworks!

platform :ios, '9.0'

target 'XYUIKit-Swift_Example' do
  pod 'XYUIKit-Swift', :path => '../'

  target 'XYUIKit-Swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
